"""Add severity

Revision ID: 3337d307037c
Revises: 3c38119e3441
Create Date: 2025-08-07 22:27:56.460483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3337d307037c'
down_revision = '3c38119e3441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('CRITICAL', 'MAJOR', 'MEDIUM', 'LOW', name='severitylevel'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.Enum('CRITICAL', 'MAJOR', 'MEDIUM', 'LOW', name='severitylevel'),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
