"""Rename Product to Case

Revision ID: 3c38119e3441
Revises: 95ede8ef731d
Create Date: 2025-08-07 22:19:23.285427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c38119e3441'
down_revision = '95ede8ef731d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('info', sa.TEXT(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_modified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
